module Contracts.ToastytradeSell exposing
    ( Committed
    , GetParameters
    , GetState
    , InitiatorStatementLog
    , PhaseChange
    , ResponderStatementLog
    , abortedFromDepositDeadlinePassedEvent
    , autorecallAvailable
    , autoreleaseAvailable
    , burn
    , burnedEvent
    , claim
    , commit
    , committedDecoder
    , committedEvent
    , depositDeadlinePassed
    , getBalance
    , getParameters
    , getParametersDecoder
    , getState
    , getStateDecoder
    , initiatorStatement
    , initiatorStatementLogDecoder
    , initiatorStatementLogEvent
    , open
    , phase
    , phaseChangeDecoder
    , phaseChangeEvent
    , phaseStartTimestamps
    , poke
    , recall
    , recalledEvent
    , release
    , releasedEvent
    , responder
    , responderStatement
    , responderStatementLogDecoder
    , responderStatementLogEvent
    , sellAmount
    )

import Abi.Decode as AbiDecode exposing (abiDecode, andMap, data, toElmDecoder, topic)
import Abi.Encode as AbiEncode exposing (Encoding(..), abiEncode)
import BigInt exposing (BigInt)
import Eth.Types exposing (..)
import Eth.Utils as U
import Json.Decode as Decode exposing (Decoder, succeed)
import Json.Decode.Pipeline exposing (custom)



{-

   This file was generated by https://github.com/cmditch/elm-ethereum-generator

-}


{-| "autorecallAvailable()" function
-}
autorecallAvailable : Address -> Call Bool
autorecallAvailable contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "autorecallAvailable()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.bool
    }


{-| "autoreleaseAvailable()" function
-}
autoreleaseAvailable : Address -> Call Bool
autoreleaseAvailable contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "autoreleaseAvailable()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.bool
    }


{-| "burn(string)" function
-}
burn : Address -> String -> Call ()
burn contractAddress note =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "burn(string)" [ AbiEncode.string note ]
    , nonce = Nothing
    , decoder = Decode.succeed ()
    }


{-| "claim(string)" function
-}
claim : Address -> String -> Call ()
claim contractAddress note =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "claim(string)" [ AbiEncode.string note ]
    , nonce = Nothing
    , decoder = Decode.succeed ()
    }


{-| "commit(string)" function
-}
commit : Address -> String -> Call ()
commit contractAddress note =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "commit(string)" [ AbiEncode.string note ]
    , nonce = Nothing
    , decoder = Decode.succeed ()
    }


{-| "depositDeadlinePassed()" function
-}
depositDeadlinePassed : Address -> Call Bool
depositDeadlinePassed contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "depositDeadlinePassed()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.bool
    }


{-| "getBalance()" function
-}
getBalance : Address -> Call BigInt
getBalance contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "getBalance()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.uint
    }


{-| "getParameters()" function
-}
type alias GetParameters =
    { initiator : Address
    , sellAmount : BigInt
    , price : BigInt
    , responderDeposit : BigInt
    , autorecallInterval : BigInt
    , depositDeadlineInterval : BigInt
    , autoreleaseInterval : BigInt
    , logisticsString : String
    }


getParameters : Address -> Call GetParameters
getParameters contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "getParameters()" []
    , nonce = Nothing
    , decoder = getParametersDecoder
    }


getParametersDecoder : Decoder GetParameters
getParametersDecoder =
    abiDecode GetParameters
        |> andMap AbiDecode.address
        |> andMap AbiDecode.uint
        |> andMap AbiDecode.uint
        |> andMap AbiDecode.uint
        |> andMap AbiDecode.uint
        |> andMap AbiDecode.uint
        |> andMap AbiDecode.uint
        |> andMap AbiDecode.string
        |> toElmDecoder


{-| "getState()" function
-}
type alias GetState =
    { balance : BigInt
    , phase : BigInt
    , phaseStartTimestamp : BigInt
    , responder : Address
    }


getState : Address -> Call GetState
getState contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "getState()" []
    , nonce = Nothing
    , decoder = getStateDecoder
    }


getStateDecoder : Decoder GetState
getStateDecoder =
    abiDecode GetState
        |> andMap AbiDecode.uint
        |> andMap AbiDecode.uint
        |> andMap AbiDecode.uint
        |> andMap AbiDecode.address
        |> toElmDecoder


{-| "initiatorStatement(string)" function
-}
initiatorStatement : Address -> String -> Call ()
initiatorStatement contractAddress statement =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "initiatorStatement(string)" [ AbiEncode.string statement ]
    , nonce = Nothing
    , decoder = Decode.succeed ()
    }


{-| "open(address,uint256,uint256,uint256,uint256,uint256,string)" function
-}
open : Address -> Address -> BigInt -> BigInt -> BigInt -> BigInt -> BigInt -> String -> Call ()
open contractAddress initiator price responderDeposit autorecallInterval depositDeadlineInterval autoreleaseInterval logisticsString =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "open(address,uint256,uint256,uint256,uint256,uint256,string)" [ AbiEncode.address initiator, AbiEncode.uint price, AbiEncode.uint responderDeposit, AbiEncode.uint autorecallInterval, AbiEncode.uint depositDeadlineInterval, AbiEncode.uint autoreleaseInterval, AbiEncode.string logisticsString ]
    , nonce = Nothing
    , decoder = Decode.succeed ()
    }


{-| "phase()" function
-}
phase : Address -> Call BigInt
phase contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "phase()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.uint
    }


{-| "phaseStartTimestamps(uint256)" function
-}
phaseStartTimestamps : Address -> BigInt -> Call BigInt
phaseStartTimestamps contractAddress a =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "phaseStartTimestamps(uint256)" [ AbiEncode.uint a ]
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.uint
    }


{-| "poke()" function
-}
poke : Address -> Call ()
poke contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "poke()" []
    , nonce = Nothing
    , decoder = Decode.succeed ()
    }


{-| "recall()" function
-}
recall : Address -> Call ()
recall contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "recall()" []
    , nonce = Nothing
    , decoder = Decode.succeed ()
    }


{-| "release()" function
-}
release : Address -> Call ()
release contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "release()" []
    , nonce = Nothing
    , decoder = Decode.succeed ()
    }


{-| "responder()" function
-}
responder : Address -> Call Address
responder contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "responder()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.address
    }


{-| "responderStatement(string)" function
-}
responderStatement : Address -> String -> Call ()
responderStatement contractAddress statement =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "responderStatement(string)" [ AbiEncode.string statement ]
    , nonce = Nothing
    , decoder = Decode.succeed ()
    }


{-| "sellAmount()" function
-}
sellAmount : Address -> Call BigInt
sellAmount contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "sellAmount()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.uint
    }


{-| "AbortedFromDepositDeadlinePassed()" event
-}
abortedFromDepositDeadlinePassedEvent : Address -> LogFilter
abortedFromDepositDeadlinePassedEvent contractAddress =
    { fromBlock = LatestBlock
    , toBlock = LatestBlock
    , address = contractAddress
    , topics = [ Just <| U.keccak256 "AbortedFromDepositDeadlinePassed()" ]
    }


{-| "Burned()" event
-}
burnedEvent : Address -> LogFilter
burnedEvent contractAddress =
    { fromBlock = LatestBlock
    , toBlock = LatestBlock
    , address = contractAddress
    , topics = [ Just <| U.keccak256 "Burned()" ]
    }


{-| "Committed(address)" event
-}
type alias Committed =
    { responder : Address }


committedEvent : Address -> LogFilter
committedEvent contractAddress =
    { fromBlock = LatestBlock
    , toBlock = LatestBlock
    , address = contractAddress
    , topics = [ Just <| U.keccak256 "Committed(address)" ]
    }


committedDecoder : Decoder Committed
committedDecoder =
    succeed Committed
        |> custom (data 0 AbiDecode.address)


{-| "InitiatorStatementLog(string)" event
-}
type alias InitiatorStatementLog =
    { statement : String }


initiatorStatementLogEvent : Address -> LogFilter
initiatorStatementLogEvent contractAddress =
    { fromBlock = LatestBlock
    , toBlock = LatestBlock
    , address = contractAddress
    , topics = [ Just <| U.keccak256 "InitiatorStatementLog(string)" ]
    }


initiatorStatementLogDecoder : Decoder InitiatorStatementLog
initiatorStatementLogDecoder =
    succeed InitiatorStatementLog
        |> custom (data 0 AbiDecode.string)


{-| "PhaseChange(uint8)" event
-}
type alias PhaseChange =
    { newPhase : BigInt }


phaseChangeEvent : Address -> LogFilter
phaseChangeEvent contractAddress =
    { fromBlock = LatestBlock
    , toBlock = LatestBlock
    , address = contractAddress
    , topics = [ Just <| U.keccak256 "PhaseChange(uint8)" ]
    }


phaseChangeDecoder : Decoder PhaseChange
phaseChangeDecoder =
    succeed PhaseChange
        |> custom (data 0 AbiDecode.uint)


{-| "Recalled()" event
-}
recalledEvent : Address -> LogFilter
recalledEvent contractAddress =
    { fromBlock = LatestBlock
    , toBlock = LatestBlock
    , address = contractAddress
    , topics = [ Just <| U.keccak256 "Recalled()" ]
    }


{-| "Released()" event
-}
releasedEvent : Address -> LogFilter
releasedEvent contractAddress =
    { fromBlock = LatestBlock
    , toBlock = LatestBlock
    , address = contractAddress
    , topics = [ Just <| U.keccak256 "Released()" ]
    }


{-| "ResponderStatementLog(string)" event
-}
type alias ResponderStatementLog =
    { statement : String }


responderStatementLogEvent : Address -> LogFilter
responderStatementLogEvent contractAddress =
    { fromBlock = LatestBlock
    , toBlock = LatestBlock
    , address = contractAddress
    , topics = [ Just <| U.keccak256 "ResponderStatementLog(string)" ]
    }


responderStatementLogDecoder : Decoder ResponderStatementLog
responderStatementLogDecoder =
    succeed ResponderStatementLog
        |> custom (data 0 AbiDecode.string)
